In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)


Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2971 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1461 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1075 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0886 - accuracy: 0.9722
Epoch 5/5
313/313 [==============================] - 0s 1ms/step - loss: 0.0729 - accuracy: 0.9763


[0.07291188091039658, 0.9763000011444092]

In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
y_pred = model.predict(x_test)

In [10]:
y_pred.shape

(10000, 10)

In [11]:
y_test.shape

(10000,)

In [12]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [13]:
y_pred

array([[1.2927821e-06, 5.0854403e-08, 1.6733460e-05, ..., 9.9997425e-01,
        9.2670398e-08, 3.1846553e-06],
       [2.7323571e-08, 6.4994005e-05, 9.9962413e-01, ..., 1.1168447e-12,
        2.7589476e-06, 1.4490611e-12],
       [1.0105805e-06, 9.9962759e-01, 4.2625030e-05, ..., 2.3716812e-04,
        6.7293571e-05, 8.1908178e-07],
       ...,
       [1.8787710e-12, 1.5382962e-10, 2.7172513e-09, ..., 3.2127205e-06,
        1.4837459e-05, 3.1838636e-04],
       [3.0444489e-09, 2.5576646e-10, 1.3280123e-11, ..., 5.0109486e-11,
        4.4420001e-05, 1.7706773e-09],
       [2.8824190e-11, 5.5567606e-11, 4.3465470e-10, ..., 3.4296835e-14,
        1.2754030e-09, 7.8056589e-12]], dtype=float32)